### ISSUE TITLE
Farsi Yeh

### ISSUE THREAD

**Issue by mustafa0x** [khaledhosny/quran-data#13]
I'm curious, is using U+06CC semantically correct, considering it's an Arabic text?

**Comment by khaledhosny** [comment]
Despite its name, there is nothing Farsi about U+06CC; it is used in many languages, and it matches the shaping behavior of Yeh in Quran today (dotless final and isolated forms). The Alternative would have been to hack the font so that U+064A behave the same, but in this text I tried to stick to standard Unicode behavior with few exceptions that I think (or thought at time) are not currently supported in Unicode.
