### ISSUE TITLE
How does this compare to the Tanzil Project

### ISSUE THREAD

**Issue by amarz45** [khaledhosny/quran-data#26]
I want to typeset the Quran in LaTeX. I'm not sure which is a better option to take the text from, [Tanzil Project], or this repository? I know that the Tanzil Project has been professionally reviewed by many people to verify its integrity. Do you think that there are no more mistakes in this data? Is there anything preferrable about this data over Tanzil's data? Thanks.

**Comment by khaledhosny** [comment]
I’m not familiar with Tanzil text and how much it follows Othmanic rasm and Unicode best practices, the two main goals of this repository. The text here is based on [KFGQC Word document](https://fonts.qurancomplex.gov.sa/wp02/%d8%ad%d9%81%d8%b5/) but updated to follow Unicode best practices, and since these changes were done automatically and have not been individually reviewed, I have the declaimer in the README file. I’m in the process of reviewing the text manually against Al-Azhar mushaf, but I have no current plans of obtaining an official certificate.
